### ISSUE TITLE
Repair buttons for movement

### ISSUE THREAD

**Issue by vokymir** [Lorem-Ipsum-Spot/spot#19]
When I click on any movement button, hold and release in a other place than the button itself, it stays "clicked".

https://github.com/Lorem-Ipsum-Spot/spot/blame/5ea582a476fa5ef42f6473a014b034bcee2635ed/website/assets/script.js#L43

![image](https://github.com/Lorem-Ipsum-Spot/spot/assets/22869857/fe98281e-2a81-4724-bbcf-c7f60fdd013d)

**Comment by Maneren** [comment]
Well, UIs generally have the feature that when you click, hold, move away, and release, it doesn't count the click. Is this the same or is it reversed?

**Comment by Minsqui** [comment]
This should be fixed with this commit:
https://github.com/Lorem-Ipsum-Spot/spot/commit/a9137415a70886a26dcbe12b957e5478955e160d

**Comment by vokymir** [comment]
> Well, UIs generally have the feature that when you click, hold, move away, and release, it doesn't count the click. Is this the same or is it reversed?

Reversed.

> This should be fixed with this commit: [a913741](https://github.com/Lorem-Ipsum-Spot/spot/commit/a9137415a70886a26dcbe12b957e5478955e160d)

Nice, but now it does a little bit redundant thing - when clicked, moved away, it changes the vector to [0,0,0] (good job), but if I move back to the button and then release, it changes the vector to [0,0,0] AGAIN. 
It's probably ok, but could possibly create issues in the future in the main program.

**Comment by Minsqui** [comment]
Added guard if, to at least prevent unnecessary event sending a graphic change, but the issue remains

**Comment by vokymir** [comment]
LGTM, good enough
